ignore:
#  - "path/to/folder"  # ignore folders and all its contents
#  - "test_*.rb"       # wildcards accepted
#  - "**/*.py"         # glob accepted
#  - "[a-z]+/test_.*"  # regexp accepted

  # Setup configuration
  - '**/psicollect/setup.py'

  # Test files
  - '**/tests'

  # Misc statistics files
  - '**/psicollect/stats'

  # Modeling files
  - '**/psicollect/classify'

  # Command-line runners
  - '**/psicollect/assigner/assign.py'
  - '**/psicollect/cataloging/catalog.py'
  - '**/psicollect/cataloging/stack.py'
  - '**/psicollect/collector/collect.py'
  - '**/psicollect/resizer/resize.py'

coverage:
  range: 50..90
  round: down
  precision: 2
  status:
    project:
      default:
        # basic
        target: 75%
