ignore:
#  - "path/to/folder"  # ignore folders and all its contents
#  - "test_*.rb"       # wildcards accepted
#  - "**/*.py"         # glob accepted
#  - "[a-z]+/test_.*"  # regexp accepted

  # Ignore command-line runners
  - '**/psic/assigner/assign.py'
  - '**/psic/cataloging/catalog.py'
  - '**/psic/collector/collect.py'
  - '**/psic/resizer/resize.py'

coverage:
  range: 40..80
  round: down
  precision: 2