scanner:
    diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors.
    linter: flake8  # Other option is flake8

flake8:
    max-line-length: 130  # Default is 79 in PEP 8
    ignore:  # Errors and warnings to ignore
        - W503  # line break before binary operator
        - W504  # line break after binary operator
        - E731  # do not assign a lambda expression, use a def
        - C406  # unnecessary list literal - rewrite as a dict literal
        - W291 	# trailing whitespace
        - W292 	# no newline at end of file
        - W293 	# blank line contains whitespace
        - W391  # blank line at end of file

no_blank_comment: False  # If True, no comment is made on PR without any errors.
descending_issues_order: False # False = Ascending line order per file, True = Descending line order per file

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: "Hello @{name}! Wowe, look at those changes! "
                # The keyword {name} is converted into the author's username
        footer: ""
    updated:  # Messages when new commits are added to the PR
        header: "Hello @{name}! Thanks for updating this PR! "
        footer: ""
    no_errors: "There are currently no PEP 8 issues detected here. Cheers! :beers: "
