matrix:
  include:
    - language: python
      cache: pip
      before_install:
      - pip install --upgrade pip
      install:
      - src/python/psic/requirements.txt
      - src/python/psic/requirements-dev.txt
      before_script:
      - pip install --upgrade tox-travis setuptools virtualenv codecov
      script: tox
      after_success: codecov

    - language: node_js
      node_js: node
      before_install:
      - cd src/dashboard/web_server
      install:
      - npm i
      - npm install --only=dev
      script:
      - node_modules/.bin/eslint . --fix
      - npm test

after_failure:
# POST all failures on the main and beta branch to Discord
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh failure $WEBHOOK_URL
