matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - cd src/python/
        - pip install -U pip
      install:
        - pip install -r requirements.txt
        - pip install -U tox-travis codecov
      script:
        - tox

    - language: python
      python: 3.7
      before_install:
        - cd src/python/
        - pip install -U pip
      install:
        - pip install -r requirements.txt
        - pip install -U tox-travis codecov
      script:
        - tox
      after_success:
        - codecov
      branches:
        exclude:
          - beta

    - language: python
      python: 3.7
      before_install:
      - cd src/python/
      - pip install -U pip
      install:
      - pip install -r requirements.txt
      - pip install -U tox-travis codecov
      script:
      - tox
      after_success:
      - codecov
      - git rebase origin/beta origin/test-travis
      branches:
        only:
        - beta

    - language: node_js
      node_js: node
      before_install:
        - cd src/dashboard/web_server
      install:
        - npm i
        - npm install --only=dev
      script:
        - node_modules/.bin/eslint .
        - npm test

  allow_failures:
    - node_js: node