matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - cd src/python/
        - pip install -U pip pipenv
      install:
        - pipenv install tox tox-travis tox-pipenv
        - pipenv install
      script:
        - tox
      after_success:
        - codecov

    - language: python
      python: 3.7
      before_install:
        - cd src/python/
        - pip install -U pipenv
      install:
        - pipenv install pipenv tox tox-travis tox-pipenv
        - pipenv install
      script:
        - tox
      after_success:
        - codecov

    - language: node_js
      node_js: node
      before_install:
        - cd src/dashboard/web_server
      install:
        - npm i
        - npm install --only=dev
      script:
        - node_modules/.bin/eslint .
        - npm test

  allow_failures:
    - node_js: node