# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.7"
  - "3.6"


before_install:
  - pip install -U pip

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

  install:
    - pip install -r requirements.txt
    - pip install -U tox-travis codecov
    - npm install --prefix ./src/dashboard/web_server ./src/dashboard/web_server

# Command to run tests, e.g. python setup.py test
script: tox

# Codecov after success
after_success: codecov

sudo: false

node_js: "12.10"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python3.7.4/lib/python3.7/site-packages
    - node_modules