matrix:
  include:
    - language: python
      python:
        - "3.6"
        - "3.7"
      before_install:
        - pip install -U pip
      install:
        - pip install -r requirements.txt
        - pip install -U tox-travis codecov
      before_script:
        - cd src/python/Poststorm_Imagery/tests
      script:
        - tox
      after_success:
        - codecov

  allow_failures:
    - language: node_js
      node_js: node
      before_install:
        - cd src/dashboard/web_server
      install:
        - npm i
      script:
        - ./node_modules/.bin/eslint .
        - npm test