site_name: 'Post-Storm Imagery'
repo_url: 'https://github.com/UNCG-CSE/Poststorm_Imagery'
site_description: 'Classification and analysis of post-storm response imagery.'
site_author: 'C-Sick Team'

site_url: 'https://post-storm-imagery.readthedocs.io/en/latest/'

nav:
    - Readme: ../README.md
    - Home: index.md

theme: readthedocs
