site_name: 'Post-Storm Imagery'
site_description: 'Classification and analysis of post-storm response imagery.'
site_author: 'P-Sick Team'
site_url: 'https://post-storm-imagery.readthedocs.io/en/latest/'

repo_url: 'https://github.com/UNCG-CSE/Poststorm_Imagery/'
edit_uri: 'edit/master/docs/'

nav:
    - Home: index.md
    - Structure: structure.md
theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    primary: 'light green'
    accent: 'light green'

# Dark theme from https://github.com/fmaida/mkdocs-material-dark-theme
# This works well wtih the admonition extension
extra_css:
    - stylesheets/extra.css

plugins:
    - search
    - git-revision-date
    - macros

markdown_extensions:
    - toc
    - admonition
    - codehilite:
        guess_lang: False
        use_pygments: True
        noclasses: True
        pygments_style: monokai
    - footnotes
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra:
    version: 1.4.0
