site_name: 'Post-Storm Imagery'
site_description: 'Classification and analysis of post-storm response imagery.'
site_author: 'P-Sick Team'
site_url: 'https://post-storm-imagery.readthedocs.io/en/latest/'

repo_url: 'https://github.com/UNCG-CSE/Poststorm_Imagery/'
edit_uri: 'edit/master/docs/'

nav:
    - Home: index.md
    - Code of Conduct: code_of_conduct.md
    - Code Conventions: contributing.md
    - Configuring Module: configure_python_path.md
    - Data Collection: collector.md
    - Cataloging Images: cataloging.md
    - Dashboard UI:
        - Instructions: dashboard/instructions.md
        - Structure: dashboard/structure.md
    - Release Drafting: release_drafting.md
    - Reports:
        - September 24th, 2019: reports/progress_report_2019-09-24.md
        - October 31th, 2019: reports/progress_report_2019-10-31.md
        - December 3rd, 2019: reports/progress_report_2019-12-03.md
    - Slides:
        - September 24th, 2019: https://docs.google.com/presentation/d/1dLTfdUjqpIh-sr0QH6XXqJRppK400PCauQl_qsmUHqk/present?includes_info_params=1&eisi=CPb9662D6eQCFYFXgQodpcoDuQ#slide=id.g1f87997393_0_782
        - October 31th, 2019: https://docs.google.com/presentation/d/1J_xktC5Rf-i9PXO-6zSJH6b0KM2t5hl4Ag_8eV1cd3Y/present?includes_info_params=1&eisi=CMSpvpK6xeUCFUvCxQodLsQLkw#slide=id.g1f87997393_0_782
        - December 3rd, 2019: https://docs.google.com/presentation/d/1_QjnVBa18QjCM7rzX_N4geD7lekv2IRtm0PoWVWbiXI/present?includes_info_params=1&eisi=CK6DrrG1muYCFYFRgQodNbIICw#slide=id.g1f87997393_0_782
theme:
  name: 'material'
  custom_dir: 'theme'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    primary: 'light green'
    accent: 'light green'

# Dark theme from https://github.com/fmaida/mkdocs-material-dark-theme
# This works well wtih the admonition extension
extra_css:
    - stylesheets/extra.css
    # - stylesheets/extra.css.map
    # - stylesheets/extra.scss
#   - stylesheets/dark_theme.css
#   - stylesheets/codehilite.css

plugins:
    - search
    - git-revision-date
    - macros

markdown_extensions:
    - toc
    - admonition
    - codehilite:
        guess_lang: False
        use_pygments: True
        noclasses: True
        pygments_style: monokai
    - footnotes
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra:
    version: 1.4.0
