site_name: 'Post-Storm Imagery'
site_description: 'Classification and analysis of post-storm response imagery.'
site_author: 'P-Sick Team'
site_url: 'https://post-storm-imagery.readthedocs.io/en/latest/'

repo_url: 'https://github.com/UNCG-CSE/Poststorm_Imagery/'
edit_uri: 'edit/beta/docs/'

nav:
    - Home: index.md
    - Code of Conduct: code_of_conduct.md
    - Code Conventions: contributing.md
    - Data Collection: collector.md
    - Cataloging Images: cataloging.md
    - Dashboard UI: dashboard.md
    - Release Drafting: release_drafting.md
    - Reports:
        - September 24th, 2019: reports/progress_report_24-09-2019.md
    - Slides:
        - September 24th, 2019: https://docs.google.com/presentation/d/1dLTfdUjqpIh-sr0QH6XXqJRppK400PCauQl_qsmUHqk/present?token=AC4w5VjKPNuxgH4Fvm43IBHer9S_VmB48g%3A1569313231926&includes_info_params=1&eisi=CPb9662D6eQCFYFXgQodpcoDuQ#slide=id.g1f87997393_0_782

theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    primary: 'light green'
    accent: 'light green'

plugins:
    - search
    - git-revision-date
    - macros

markdown_extensions:
    - toc
    - admonition
    - codehilite
    - footnotes
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra:
    version: 1.1.0
