site_name: 'Post-Storm Imagery'
repo_url: 'https://github.com/UNCG-CSE/Poststorm_Imagery'
site_description: 'Classification and analysis of post-storm response imagery.'
site_author: 'C-Sick Team'

site_url: 'https://post-storm-imagery.readthedocs.io/en/latest/'

nav:
    - Home: https://raw.githubusercontent.com/UNCG-CSE/Poststorm_Imagery/master/README.md
    - Code of Conduct: code_of_conduct.md
    - Code Conventions: contributing.md
    - Data Collection: collector.md

theme: readthedocs

plugins:
    - search
    - git-revision-date
    - macros

extra:
    version: 1.0.0
