ignore:
#  - "path/to/folder"  # ignore folders and all its contents
#  - "test_*.rb"       # wildcards accepted
#  - "**/*.py"         # glob accepted
#  - "[a-z]+/test_.*"  # regexp accepted
  - "src/python/Poststorm_Imagery/collector/collect.py"
  - "test_*.py"

coverage:
  range: 50..85
  round: down
  precision: 2

codecov:
  token: 87c8d6f0-226a-4ea4-a98d-eef1a184376c